---

- name: provision server
  hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: Software is installed
      yum:
        name:
          - httpd
          - git
        state: present

    - name: Repo is checked out
      git:
        repo: https://github.com/ultral/2048.git
        dest: /var/www/html
        force: true

    - name: Access via HTTP is allowed
      firewalld:
        service: http
        permanent: yes
        state: enabled
        
    - name: Access via 8080 port and 80 port
      firewalld:
        port: "{{ item.port }}"
        permanent: yes
        immediate: yes
        state: enabled
      with_items:
        - { port: '8080/tcp' }
        - { port: '80/tcp' }

    - name: reload service firewalld
      systemd:
        name: firewalld
        state: reloaded
        
    - name: Httpd is started
      systemd:
        name: httpd
        state: started

    - name: Print message
      debug:
        msg: "Site locates at http://localhost:8080/"