---

- name: Install 2048
  hosts: all
  become: true
  become_user: root
  vars:
    user:
      login: deploy
      password_hash:
        "$6$NwI7op8FHR1VQta6$zuQXHtNtM/7SRQsf1./18WbBrHMq4mT88nWh67ThmlWcqyVX3F\
        BTY9uj/07tR9ViDEvjg6/bh0y3mSjeDQYe3."
      authorized_key:
        "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr\
        +kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6I\
        edplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2\
        hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZE\
        nDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHln\
        VYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key"

  tasks:
    - name: Create account for deploy
      user:
        name: "{{ user.login }}"
        shell: /bin/bash
        update_password: always
        password: "{{ user.password_hash }}"

    - name: Add deploy user to sudoers
      lineinfile:
        path: /etc/sudoers
        state: present
        line: "{{ user.login }} ALL=(ALL:ALL) NOPASSWD:ALL"
        validate: visudo -cf %s

    - name: Create folder structure for SSH keys
      file:
        path: /home/"{{ user.login }}"/.ssh
        state: directory
        mode: '0700'

    - name: Create authorized key for user deploy
      authorized_key:
        user: "{{ user.login }}"
        state: present
        key: "{{ user.authorized_key }}"

    - name: Set permission to SSH keys
      file:
        path: /home/{{ user.login }}/.ssh/authorized_keys
        mode: '0600'

    - name: Set appropriate permissions to SSH keys folder
      file:
        path: /home/{{ user.login }}/.ssh
        owner: deploy
        group: deploy
        recurse: yes

    - name: Install software
      package:
        name:
          - httpd
          - git
          - iptables-services
          - net-snmp
          - net-snmp-utils
        state: present

    - name: Checkout git repository
      git:
        repo: https://github.com/ultral/2048.git
        dest: /var/www/html
        force: true
        version: fc1ef4fe5a5fcccea7590f3e4c187c75980b353f

    - name: Configure SNMPD
      blockinfile:
        path: /etc/snmp/snmpd.conf
        state: present
        block: | 
          syslocation Server Room
          syscontact SysAdmin (devops@example.com)
          rocommunity snmp_secret_rocommunity
        insertafter: EOF

    - name: Allow access via HTTP
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: '80'
        ctstate: NEW
        jump: ACCEPT

    - name: Allow access via SNMP
      iptables:
        chain: INPUT
        protocol: udp
        destination_port: '161'
        ctstate: NEW
        jump: ACCEPT

    - name: Start httpd
      systemd:
        name: httpd
        state: started

    - name: Start snmpd
      systemd:
        name: snmpd
        state: started

    - name: Print message
      debug:
        msg: "Play 2028: http://localhost:8080/"