---

- name: Install 2048
  hosts: all
  become: true
  become_user: root
  vars:
    iptables_allowed_ports:
      # default
      - {protocol: tcp, port: 180}
      - {protocol: tcp, port: 1443}
      - {protocol: udp, port: 1161}
      # task3.3
      - {protocol: udp, port: 161}
      - {protocol: tcp, port: 443}
      # httpd
      - {protocol: tcp, port: 80}
    sshgroup_name: sshusers
    user:
      login: deploy
      password_hash:
        "$6$NwI7op8FHR1VQta6$zuQXHtNtM/7SRQsf1./18WbBrHMq4mT88nWh67ThmlWcqyVX3\
        FBTY9uj/07tR9ViDEvjg6/bh0y3mSjeDQYe3."
      authorized_key:
        "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YV\
        r+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv\
        6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn\
        5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0\
        jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE9\
        8OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key"
    snmpd_config:
      - {access: rocommunity, community: public, address: 127.0.0.1}
      - {access: rocommunity, community: private, address: 192.168.1.1}
  tasks:
    - name: Create admin user
      import_tasks: provision_users.yml
    - name: Install software
      import_tasks: provision_software.yml
    - name: Configure iptables
      import_tasks: provision_iptables.yml
    - name: Install game 2048
      import_tasks: provision_site.yml
    - name: Print message
      debug:
        msg: "Play 2028: http://localhost:8080/"
