---
- name: install snmpd
  yum:
    name:
      - net-snmp
      - net-snmp-utils
    state: present
  when: ansible_distribution == 'CentOS'

- name: configure snmpd
  template:
    src: snmpd.conf.j2
    dest: "/etc/snmp/snmpd.conf"
  become: yes    
  when: ansible_distribution == 'CentOS'
