---

- hosts: localhost
  roles:
    - role: example_plugins
  vars:
    admins:
      - login: login1
        email: dep@loy.me
      - login: login2
      - login: login3
        email: dep@loy.com
      - login: login4
  tasks:
    - debug:
        msg: "{{ admins }}"
    # print all acounts without email
    - debug:
        msg:
          "{% set out_list = [] %}\
          {% for user in admins %}\
          {% if not user.email is defined %}\
          {{ out_list.append(user.login) }}\
          {% endif %}\
          {% endfor %}\
          {{ out_list }}"

    # use standard jinja2 filters
    - debug:
        msg: >-
          {{ admins |
            selectattr('email', 'undefined') |
            map(attribute='login') |
            list }}

    # use test plugin
    - debug:
        msg: >-
          {{ admins |
            select('has_email') |
            map(attribute='login') |
            list }}

    # use filter
    - debug:
        msg: "{{ admins | users_without_email }}"

    # use filter from NBaranov
    - debug:
        msg: "{{ admins | users_without_hash }}"

