---

- name: provision server
  hosts: all
  become: true
  become_user: root
  vars:
    iptables_allowed_ports:
      - {protocol: tcp, port: 80}
      - {protocol: tcp, port: 443}
      - {protocol: udp, port: 161}
  roles:
    - role: users
    - role: game2048
